
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InpBjybWebSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InpBjybWebSoap {


    /**
     * 电子凭证获取信息 reqStr 请求信息
     * 
     * @param reqStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PostQrGetPersonInfo", action = "http://tempuri.org/PostQrGetPersonInfo")
    @WebResult(name = "PostQrGetPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostQrGetPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostQrGetPersonInfo")
    @ResponseWrapper(localName = "PostQrGetPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostQrGetPersonInfoResponse")
    public String postQrGetPersonInfo(
        @WebParam(name = "reqStr", targetNamespace = "http://tempuri.org/")
        String reqStr);

    /**
     * 证件号获取信息 reqStr 请求信息
     * 
     * @param reqStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PostIdNoGetPersonInfo", action = "http://tempuri.org/PostIdNoGetPersonInfo")
    @WebResult(name = "PostIdNoGetPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostIdNoGetPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostIdNoGetPersonInfo")
    @ResponseWrapper(localName = "PostIdNoGetPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostIdNoGetPersonInfoResponse")
    public String postIdNoGetPersonInfo(
        @WebParam(name = "reqStr", targetNamespace = "http://tempuri.org/")
        String reqStr);

}
