
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InpBjybWeb", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/Users/jasonj/software/develop-tools/idea-workspace/spring-projects/java-advance-share-club/spring-projects/spring-project-tests/spring-webservice-tests/holidayService/src/test/resources/wsdl/test.wsdl")
public class InpBjybWeb
    extends Service
{

    private final static URL INPBJYBWEB_WSDL_LOCATION;
    private final static WebServiceException INPBJYBWEB_EXCEPTION;
    private final static QName INPBJYBWEB_QNAME = new QName("http://tempuri.org/", "InpBjybWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/jasonj/software/develop-tools/idea-workspace/spring-projects/java-advance-share-club/spring-projects/spring-project-tests/spring-webservice-tests/holidayService/src/test/resources/wsdl/test.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INPBJYBWEB_WSDL_LOCATION = url;
        INPBJYBWEB_EXCEPTION = e;
    }

    public InpBjybWeb() {
        super(__getWsdlLocation(), INPBJYBWEB_QNAME);
    }

    public InpBjybWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), INPBJYBWEB_QNAME, features);
    }

    public InpBjybWeb(URL wsdlLocation) {
        super(wsdlLocation, INPBJYBWEB_QNAME);
    }

    public InpBjybWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INPBJYBWEB_QNAME, features);
    }

    public InpBjybWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InpBjybWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InpBjybWebSoap
     */
    @WebEndpoint(name = "InpBjybWebSoap")
    public InpBjybWebSoap getInpBjybWebSoap() {
        return super.getPort(new QName("http://tempuri.org/", "InpBjybWebSoap"), InpBjybWebSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InpBjybWebSoap
     */
    @WebEndpoint(name = "InpBjybWebSoap")
    public InpBjybWebSoap getInpBjybWebSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "InpBjybWebSoap"), InpBjybWebSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INPBJYBWEB_EXCEPTION!= null) {
            throw INPBJYBWEB_EXCEPTION;
        }
        return INPBJYBWEB_WSDL_LOCATION;
    }

}
